Repository capstone-maru/maru-front-end, pull requests merged in 2024-05, with the labels that each got.

#72 feat: Apply changes to the Shared API, Add the create mate card form when writing a post
  .eslintrc.json
  public/kakao-login.png
  public/landing-page-image.png
  public/naver-login.png
  src/app/layout.tsx
  src/app/lib/axios-interceptor.ts
  src/app/lib/providers/AuthProvider.tsx
  src/app/pages/landing-page.tsx
  src/app/pages/setting-page.tsx
  src/app/pages/user-input-page.tsx
  src/app/pages/writing-post-page.tsx
  src/components/NavigationBar.tsx
  src/components/UserInputSection.tsx
  src/components/card/OptionSection.tsx
  src/components/card/VitalSection.tsx
  src/entities/shared-post/shared-post.type.ts
  src/features/shared/shared.api.ts
  src/features/shared/shared.dto.ts
  src/features/shared/shared.hook.ts
  src/features/shared/shared.type.ts
  src/shared/types/floor-type.ts
  src/shared/types/index.ts
  src/shared/types/room-type.ts
Labels: enhancement

#76 feat: Add filter state when fetching posts.
  src/app/layout.tsx
  src/app/lib/providers/AuthProvider.tsx
  src/app/pages/setting-page.tsx
  src/app/pages/shared-posts-page.tsx
  src/app/pages/user-input-page.tsx
  src/app/pages/writing-post-page.tsx
  src/components/NavigationBar.tsx
  src/components/card/OptionSection.tsx
  src/components/shared-posts/filter/DealTypeFilter.tsx
  src/components/shared-posts/filter/ExtraInfoFilter.tsx
  src/components/shared-posts/filter/RoomTypeFilter.tsx
  src/entities/shared-post/shared-post.type.ts
  src/entities/shared-posts-filter/shared-posts-filter.atom.ts
  src/entities/shared-posts-filter/shared-posts-filter.hook.ts
  src/entities/shared-posts-filter/shared-posts-filter.type.ts
  src/features/shared/shared.api.ts
  src/features/shared/shared.hook.ts
  src/features/shared/shared.type.ts
  src/shared/debounce/debounce.hook.ts
  src/shared/debounce/index.ts
  src/shared/types/floor-type.ts
  src/shared/types/index.ts
  src/shared/types/rental-type.ts
  src/shared/types/room-type.ts
Labels: enhancement

#82 feat/fix: Apply changes to the Shared API
  src/app/layout.tsx
  src/app/lib/providers/AuthProvider.tsx
  src/app/lib/providers/InitializationProvider.tsx
  src/app/lib/providers/index.ts
  src/app/pages/main-page.tsx
  src/app/pages/shared-post-page.tsx
  src/app/pages/shared-posts-page.tsx
  src/app/pages/writing-post-page.tsx
  src/app/shared/dormitory/[postId]/page.tsx
  src/app/shared/room/[postId]/page.tsx
  src/app/shared/writing/dormitory/[postId]/page.tsx
  src/app/shared/writing/dormitory/page.tsx
  src/app/shared/writing/room/[postId]/page.tsx
  src/app/shared/writing/room/page.tsx
  src/components/CircularProfileImage.tsx
  src/components/RangeSlider.tsx
  src/components/chat/ChattingRoom.tsx
  src/components/shared-post-page/CardToggleButton.tsx
  src/components/shared-post-page/ImageGrid.tsx
  src/components/shared-posts/PostCard.tsx
  src/components/shared-posts/SharedPostsMenu.tsx
  src/components/shared-posts/filter/RoomTypeFilter.tsx
  src/entities/shared-post/shared-post.type.ts
  src/entities/shared-posts-filter/shared-posts-filter.atom.ts
  src/entities/shared-posts-filter/shared-posts-filter.hook.ts
  src/entities/shared-posts-filter/shared-posts-filter.type.ts
  src/entities/user/user.type.ts
  src/features/auth/auth.dto.ts
  src/features/shared/shared.api.ts
  src/features/shared/shared.atom.ts
  src/features/shared/shared.hook.ts
  src/features/shared/shared.type.ts
Labels: enhancement

#89 feat: Apply recommendation system
  src/app/layout.tsx
  src/app/lib/providers/InitializationProvider.tsx
  src/app/pages/main-page.tsx
  src/app/pages/mobile/mobile-main-page.tsx
  src/app/pages/mobile/mobile-shared-posts-page.tsx
  src/app/pages/shared-post-page.tsx
  src/app/pages/shared-posts-page.tsx
  src/components/NavigationBar.tsx
  src/components/chat/ChattingRoom.tsx
  src/components/main-page/UserCard.tsx
  src/components/shared-posts/PostCard.tsx
  src/components/shared-posts/SharedPostFilters.tsx
  src/components/shared-posts/SharedPostsMenu.tsx
  src/components/shared-posts/filter/MateCardFilter.tsx
  src/entities/shared-post/shared-post.type.ts
  src/features/profile/profile.api.ts
  src/features/profile/profile.dto.ts
  src/features/profile/profile.hook.ts
  src/features/recommendation/index.ts
  src/features/recommendation/recommendation.api.ts
  src/features/recommendation/recommendation.dto.ts
  src/features/recommendation/recommendation.hook.ts
  src/features/shared/shared.api.ts
  src/features/shared/shared.hook.ts
  src/features/shared/shared.type.ts
Labels: enhancement

#97 fix: Change the layout from desktop to tablet
  src/app/globals.scss
  src/app/pages/landing-page.tsx
  src/app/pages/main-page.tsx
  src/app/pages/profile-page.tsx
  src/app/pages/shared-posts-page.tsx
  src/app/pages/user-input-page.tsx
  src/components/NavigationBar.tsx
  src/components/shared-posts/SharedPostFilters.tsx
  src/components/shared-posts/SharedPostsMenu.tsx
  src/components/shared-posts/filter/ExtraInfoFilter.tsx
Labels: enhancement

#98 feat: Add Error Handling
  src/app/layout.tsx
  src/app/lib/axios.ts
  src/app/lib/providers/InitializationProvider.tsx
  src/app/pages/main-page.tsx
  src/app/pages/mobile/mobile-main-page.tsx
  src/app/pages/mobile/mobile-shared-posts-page.tsx
  src/app/pages/shared-posts-page.tsx
  src/app/pages/user-input-page.tsx
  src/features/shared/shared.api.ts
Labels: enhancement

#99 release: v0.7.0
  package.json
  src/app/globals.scss
  src/app/layout.tsx
  src/app/lib/axios.ts
  src/app/lib/providers/InitializationProvider.tsx
  src/app/pages/landing-page.tsx
  src/app/pages/main-page.tsx
  src/app/pages/mobile/mobile-main-page.tsx
  src/app/pages/mobile/mobile-shared-post-page.tsx
  src/app/pages/mobile/mobile-shared-posts-page.tsx
  src/app/pages/profile-page.tsx
  src/app/pages/shared-post-page.tsx
  src/app/pages/shared-posts-page.tsx
  src/app/pages/user-input-page.tsx
  src/app/pages/writing-post-page.tsx
  src/components/FloatingChatting.tsx
  src/components/NavigationBar.tsx
  src/components/RangeSlider.tsx
  src/components/shared-posts/SharedPostFilters.tsx
  src/components/shared-posts/SharedPostsMenu.tsx
  src/components/shared-posts/filter/DealTypeFilter.tsx
  src/components/shared-posts/filter/ExtraInfoFilter.tsx
  src/components/shared-posts/filter/RoomTypeFilter.tsx
  src/features/shared/shared.api.ts
  src/features/shared/shared.hook.ts
Labels: release

#105 feat: Add the feature to add mates
  public/icon-check.svg
  src/app/pages/mobile/mobile-profile-page.tsx
  src/app/pages/mobile/mobile-shared-post-page.tsx
  src/app/pages/mobile/mobile-writing-post-page.tsx
  src/app/pages/profile-page.tsx
  src/app/pages/shared-post-page.tsx
  src/app/pages/writing-post-page.tsx
  src/components/NavigationBar.tsx
  src/components/writing-post-page/MateSearchBox.tsx
  src/features/auth/auth.hook.ts
  src/features/chat/chat.hook.ts
  src/features/profile/profile.api.ts
  src/features/profile/profile.dto.ts
  src/features/profile/profile.hook.ts
  src/features/shared/shared.atom.ts
  src/features/shared/shared.hook.ts
Labels: enhancement

#107 release: v0.8.0
  package.json
  public/icon-check.svg
  public/profile_img.png
  public/profile_img_nonpercent.png
  src/app/error/page.tsx
  src/app/lib/axios.ts
  src/app/pages/error-page.tsx
  src/app/pages/index.ts
  src/app/pages/mobile/mobile-main-page.tsx
  src/app/pages/mobile/mobile-profile-page.tsx
  src/app/pages/mobile/mobile-setting-page.tsx
  src/app/pages/mobile/mobile-shared-post-page.tsx
  src/app/pages/mobile/mobile-user-input-page.tsx
  src/app/pages/mobile/mobile-writing-post-page.tsx
  src/app/pages/profile-page.tsx
  src/app/pages/setting-page.tsx
  src/app/pages/shared-post-page.tsx
  src/app/pages/user-input-page.tsx
  src/app/pages/writing-post-page.tsx
  src/components/CircularProfileImage.tsx
  src/components/FloatingChatting.tsx
  src/components/NavigationBar.tsx
  src/components/UserSearchBox.tsx
  src/components/card/OptionSection.tsx
  src/components/card/Slider.tsx
  src/components/card/VitalSection.tsx
  src/components/chat/ChatMenu.tsx
  src/components/chat/ChattingList.tsx
  src/components/chat/ChattingRoom.tsx
  src/components/chat/ReceiverMessage.tsx
  src/components/chat/SenderMessage.tsx
  src/components/shared-posts/PostCard.tsx
  src/components/writing-post-page/LocationSearchBox.tsx
  src/components/writing-post-page/MateSearchBox.tsx
  src/features/auth/auth.hook.ts
  src/features/chat/chat.api.ts
  src/features/chat/chat.hook.ts
  src/features/geocoding/geocoding.api.ts
  src/features/profile/profile.api.ts
  src/features/profile/profile.dto.ts
  src/features/profile/profile.hook.ts
  src/features/shared/shared.atom.ts
  src/features/shared/shared.hook.ts
Labels: enhancement

#111 release: v0.9.1
  package.json
Labels: release

#112 release: v0.10.0
  package.json
  src/app/pages/main-page.tsx
  src/app/pages/mobile/mobile-main-page.tsx
  src/app/pages/shared-posts-page.tsx
  src/components/CircularProfileImage.tsx
  src/components/main-page/UserCard.tsx
Labels: release

#113 release: v0.10.1
  package.json
  src/app/House.ico
  src/app/favicon.ico
  src/app/layout.tsx
Labels: release

#115 release: v0.11.1
  .eslintrc.json
  package.json
  src/app/not-found.tsx
  src/app/pages/main-page.tsx
  src/app/pages/mobile/mobile-main-page.tsx
  src/app/pages/mobile/mobile-profile-page.tsx
  src/app/pages/mobile/mobile-shared-posts-page.tsx
  src/app/pages/profile-page.tsx
  src/app/pages/shared-post-page.tsx
  src/app/pages/shared-posts-page.tsx
  src/components/CircularProfileImage.tsx
  src/components/main-page/UserCard.tsx
  yarn.lock
Labels: enhancement, fix

#118 release: v0.11.2
  package.json
  src/app/pages/main-page.tsx
  src/app/pages/mobile/mobile-main-page.tsx
  src/app/pages/mobile/mobile-shared-posts-page.tsx
  src/app/pages/shared-posts-page.tsx
  src/components/SearchBox.tsx
  src/components/UserSearchBox.tsx
  src/components/chat/ChattingRoom.tsx
  src/components/chat/ReceiverMessage.tsx
  src/components/chat/SenderMessage.tsx
  src/features/profile/profile.api.ts
  src/features/profile/profile.hook.ts
  src/features/shared/shared.api.ts
  src/features/shared/shared.hook.ts
  yarn.lock
Labels: enhancement
